### ISSUE TITLE
Webhook secret is not a comming from env

### ISSUE THREAD

**Issue by hassanad94** [michaelshimeles/react-local-first-hono#1]
When i try to run the project. I could not save my users, bacause the webhook secret wast pointing to my instance

Its and easy change. I have made a brach, but i dont have permission.
![Screenshot 2024-12-03 at 11 46 00](https://github.com/user-attachments/assets/16dee15a-fad8-4d0d-8cb4-4a9adcac0344)

**Comment by michaelshimeles** [comment]
oopsieeee

thanks for the fix
